spring.application.name=moneymanager

# ===============================
# SERVER
# ===============================
server.port=8090

# ===============================
# DATASOURCE (PostgreSQL / Neon)
# ===============================
spring.datasource.url=${DB_URI}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CONNECTION POOL (HikariCP)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

# ===============================
# MAILJET SMTP CONFIGURATION
# ===============================

spring.mail.host=in-v3.mailjet.com
spring.mail.port=587

# Mailjet SMTP credentials
spring.mail.username=${MAILJET_API_KEY}
spring.mail.password=${MAILJET_SECRET_KEY}

# ===============================
# SMTP PROPERTIES
# ===============================

spring.mail.protocol=smtp
spring.mail.default-encoding=UTF-8

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
spring.mail.properties.mail.smtp.from=${MAILJET_MAIL_FROM}

# ===============================
# DEBUG (disable in production)
# ===============================
spring.mail.properties.mail.debug=true
logging.level.org.springframework.web=DEBUG


jwt.secret=${JWT_SECRET_KEY}
jwt.expiration=86400000